keepalived_group: WAN_LAN_2
keepalived_auth_pass: <pass>
keepalived_routerid: 3

bind_interface: ens8
keepalived_priority: 90
keepalived_state: SLAVE
track_interface: ens192
vips:
  - vip: 10.0.0.100
    device: ens8

track_scripts:
  - name: check_haproxy
    process: haproxy
